FROM alpine
RUN mkdir /a
RUN mkdir /b
WORKDIR /a
RUN echo "test" > test.txt
RUN echo "test2" > test2.txt
RUN echo "test3" >> test2.txt
WORKDIR /b
RUN echo "test" > test.txt
ENTRYPOINT [echo, "hello world!"]